apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.mysql.credentials.username }}
  password: {{ .Values.mysql.credentials.password }}
  root-password: {{ .Values.mysql.credentials.rootPassword }}
