apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-wordpress-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.wordpress.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.wordpress.storage.size }}
